# Generated by Django 5.0.7 on 2024-07-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('year', models.IntegerField()),
                ('image', models.FileField(upload_to='student_images/')),
                ('admission_number', models.CharField(max_length=30)),
                ('unique_number', models.CharField(max_length=30)),
                ('parent_phone_number', models.BigIntegerField()),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.BigIntegerField()),
                ('capacity', models.IntegerField()),
                ('HOSTEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.hostel')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('screenshot', models.FileField(upload_to='payment_screenshots/')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='parent_images/')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.logintable')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
            ],
        ),
        migrations.CreateModel(
            name='LocalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.TimeField()),
                ('entry_time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('image', models.FileField(upload_to='tutor_images/')),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.department')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='LeavingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
                ('TUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('photo', models.FileField(upload_to='warden_photos/')),
                ('HOSTEL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.hostel')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.logintable')),
            ],
        ),
    ]
