# Generated by Django 5.0.7 on 2024-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0004_rename_photo_warden_image_room_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.FileField(upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='warden',
            name='image',
            field=models.FileField(upload_to='warden_images/'),
        ),
    ]
