# Generated by Django 5.0.7 on 2024-08-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0006_notification_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='DEPARTMENT',
        ),
        migrations.RemoveField(
            model_name='student',
            name='HOSTEL',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='DEPARTMENT',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.FileField(default=1, upload_to='department_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=30)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='COURSE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='COURSE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.course'),
            preserve_default=False,
        ),
    ]
