# Generated by Django 5.0.7 on 2024-08-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0009_alter_complaint_image_alter_department_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warden',
            name='HOSTEL',
        ),
        migrations.AddField(
            model_name='hostel',
            name='WARDEN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_project.warden'),
        ),
    ]
