# Generated by Django 5.0.7 on 2024-08-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0010_remove_warden_hostel_hostel_warden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='WARDEN',
        ),
        migrations.AddField(
            model_name='warden',
            name='HOSTEL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_project.hostel'),
        ),
    ]
