# Generated by Django 5.0.7 on 2024-08-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0011_remove_hostel_warden_warden_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_duration',
        ),
    ]
