# Generated by Django 5.0.7 on 2024-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0012_remove_course_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
