# Generated by Django 5.0.7 on 2024-08-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0014_remove_department_type_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateComer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ROOM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.room')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student')),
            ],
        ),
    ]
