# Generated by Django 5.0.7 on 2024-08-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0015_latecomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latecomer',
            name='STUDENT',
        ),
    ]
