# Generated by Django 5.0.7 on 2024-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0016_remove_latecomer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='unique_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='replied_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
