# Generated by Django 5.0.7 on 2024-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0017_remove_student_unique_number_payment_is_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
