# Generated by Django 5.0.7 on 2024-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0018_alter_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='address',
        ),
        migrations.AddField(
            model_name='hostel',
            name='details',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
