# Generated by Django 5.0.7 on 2024-09-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0019_remove_hostel_address_hostel_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
