# Generated by Django 5.0.7 on 2024-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0022_remove_hostel_course_hostel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='COURSE',
            field=models.ManyToManyField(related_name='hostels', to='hostel_project.course'),
        ),
    ]
