# Generated by Django 5.0.7 on 2024-09-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_project', '0023_alter_hostel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='HOSTEL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.hostel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='STUDENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_project.student'),
        ),
    ]
